[project]
name = "my-todo-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.128.5",
    "psycopg2-binary>=2.9.11",
    "sqlmodel>=0.0.32",
    "uvicorn>=0.40.0",
]
